### PR TITLE
KTOR-638 KTOR-2616 Fix flaky bind exception triggered by early socket…

### LINKED ISSUE #1049: aSocket().bind() sometimes throws Already bound SocketException
### Ktor Version
1.1.3

### Ktor Engine Used
Netty, Socket

### JVM Version, Operating System and Relevant Context
openjdk version "10.0.2" 2018-07-17, Ubuntu 18.04.2 LTS

### Feedback
It's hard to reproduce, the problem appears and disappears without observable reasons. I have a server starting two Netty instances and one UDP socket

```
fun Application.main() {
    embeddedServer(Netty, port = 18080) {
        routing {
            get("/") {
                call.respondText("Hello World from what is supposed to be WWW server!", ContentType.Text.Plain)
            }
        }
    }.start()
    embeddedServer(Netty, port = 18090) {
        routing {
            get("/") {
                call.respondText("Hello World from what is supposed to be RESt server!", ContentType.Text.Plain)
            }
        }
    }.start()
    runBlocking {
        org.looksworking.ha.controller.Application.logger.info("Starting UDP")
        val server = aSocket(ActorSelectorManager(Dispatchers.IO))
            .udp()
            .bind(InetSocketAddress("0.0.0.0", 18070))
        while (true) {
            println(server.incoming.receive().packet.readText())
        }
    }
}
```

Console output:

```
...
Starting UDP
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:349)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:299)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:275)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:127)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:247)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:106)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:18)
	at io.ktor.server.engine.ApplicationEngine$DefaultImpls.start$default(ApplicationEngine.kt:52)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:17)
Caused by: java.net.SocketException: Already bound
	at java.base/sun.nio.ch.Net.translateToSocketException(Net.java:136)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:93)
	at io.ktor.network.sockets.UDPSocketBuilder.bind(Builders.kt:150)
	at io.ktor.network.sockets.UDPSocketBuilder.bind$default(Builders.kt:141)
	at org.looksworking.ha.controller.AppKt$main$3.invokeSuspend(App.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.looksworking.ha.controller.AppKt.main(App.kt:38)
	... 18 more
Caused by: java.nio.channels.AlreadyBoundException
	at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:669)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:91)
	... 30 more
```

I checked many times - no other instance is running, no ports are busy. At the same time, tcp ports are successfully taken, while this problem with udp socket sometimes persists even after reboot. And then just goes away without any changes.
Is it possible that like in most upvoted answer [here](https://stackoverflow.com/questions/13374239/receiving-udp-data-in-java), ktor sometimes creates an already bound socket?

### PR DESCRIPTION
**Pull request by e5l**
Fix [KTOR-638](https://youtrack.jetbrains.com/issue/KTOR-638) [KTOR-2616](https://youtrack.jetbrains.com/issue/KTOR-2616)
Fix #1049

### CODE REVIEW

File: ktor-network/jvm/test/io/ktor/network/sockets/tests/UDPSocketTest.kt [hunk 1]
```diff
@@ -41,195 +39,181 @@ class UDPSocketTest : CoroutineScope {
...
-            }
+    @Test
+    fun testBind() {
+        val socketBuilder: UDPSocketBuilder = aSocket(ActorSelectorManager(Dispatchers.IO)).udp()
+        val socket = socketBuilder.bind()
+        val port = socket.localAddress.port
+        socket.close()
+
+        repeat(1024) {
+            println(it)
```
Comment (rsinukov) [inline ktor-network/jvm/test/io/ktor/network/sockets/tests/UDPSocketTest.kt:212]: please remove `println`

**Review by rsinukov — APPROVED** [review]

**Comment by rsinukov** [comment]
Please check CI build
