### PR TITLE
Use comma to divide headers (Fix #1765).

### LINKED ISSUE #1765: Ktor client: Accept header mime-types should be separated with a comma
**Ktor Version and Engine Used (client or server and name)**
1.3.2, Client Apache

**Describe the bug**
When sending `Accept` header with multiple mime-types they are separated with a semicolon instead of a comma.

**To Reproduce**
This code:
```
val result: String = HttpClient(Apache).post("http://localhost:9000") {
    contentType(ContentType.Application.Json)
    accept(ContentType.Application.Xml)
    accept(ContentType.Application.Json)
    body = "{}"
}
```
generates the following request:
```
POST / HTTP/1.1
Accept: application/xml;application/json
Accept-Charset: UTF-8
User-Agent: Ktor client
Content-Length: 2
Content-Type: application/json
Host: localhost:9000
Connection: Keep-Alive

{}
```

**Expected behavior**
The `Accept` header should be:
```
Accept: application/xml, application/json
```

### PR DESCRIPTION
**Pull request by dmitrievanthony**
**Subsystem**
Client Utils

**Motivation**
The issue described in https://github.com/ktorio/ktor/issues/1765 and [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

### CODE REVIEW

File: ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/engine/UtilsTest.kt [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+package io.ktor.client.tests.engine
+
+import io.ktor.client.engine.*
+import io.ktor.client.utils.*
+import io.ktor.http.*
+import kotlin.test.*
+
+class UtilsTest {
+    @Test
+    fun testMergeHeaders() {
```
Comment (e5l) [inline ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/engine/UtilsTest.kt:14]: Could you add an end-to-end test with a socket server for all engines as well?

Comment (dmitrievanthony) [reply ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/engine/UtilsTest.kt:14]: I added several tests, please have a look.
