### PR TITLE
Don't send Authorization after redirect

### LINKED ISSUE #1467: Ktor client resends auth data to redirect location
**Ktor Version and Engine Used**
Ktor HTTP client 1.2.5 with Apache engine.

**Describe the bug**

Enable `followRedirects` for http client and send request with auth data to the host `https://foo/redirect` which redirects to the host `https://bar` with auth data from host `foo`.

**To Reproduce**

```
HttpClient(Apache) {
        followRedirects = true
    }.use { httpClient ->
    httpClient.get<HttpResponse>("https://foo/redirect") {
        basicAuthorization("login", "***")
    }
}
```

Actual result: `Authorization` header data is leaked to the host `https://bar`.

**Expected behavior**
The `Authorization` header from original request to the host `foo` is cleared before establishing redirect request to the host `bar`. It's a good security practice.

**Comment**
It could be solved by cleaning the `Authorization` header in the `HttpRedirect` feature:
https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt#L39

### PR DESCRIPTION
**Pull request by e5l**
Fix #1467

### CODE REVIEW

File: ktor-http/common/src/io/ktor/http/URLBuilder.kt [hunk 1]
```diff
@@ -160,3 +160,47 @@ data class Url(
...
+            append(it)
+        }
+
+        if (isNotEmpty()) {
+            append('@')
+        }
+
+        append(host)
+        append(':')
+        append(port)
```
Comment (cy6erGn0m) [inline ktor-http/common/src/io/ktor/http/URLBuilder.kt]: Well, we may add `0` here while we don't do the same for `Url` that is always resolved to a specific port

File: ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt [hunk 2]
```diff
@@ -31,13 +48,26 @@ class HttpRedirect {
...
                 val location = call.response.headers[HttpHeaders.Location]
 
                 val requestBuilder = HttpRequestBuilder().apply {
                     takeFrom(origin.request)
                     url.parameters.clear()
 
+                    /**
+                     * Disallow redirect with a security downgrade.
+                     */
+                    if (originProtocol.isSecure() && !url.protocol.isSecure()) {
```
Comment (cy6erGn0m) [inline ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt]: We need a switch to be able to allow downgrading

File: ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt [hunk 3]
```diff
@@ -7,22 +7,39 @@ package io.ktor.client.features
...
 class HttpRedirect {
+    /**
+     * Check if the HTTP method is allowed for redirect.
+     * Only [HttpMethod.Get] and [HttpMethod.Head] is allowed for implicit redirect.
+     *
+     * Please note: changing this flag could lead to security issues, consider changing the request URL instead.
+     */
+    @KtorExperimentalAPI
+    @Volatile
+    var checkHttpMethod: Boolean = true
```
Comment (cy6erGn0m) [inline ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt]: This may work well with REST API, however, in good old web app, it was a common pattern to do a redirect after posting form. So it is wise to keep this switch.

File: ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt [hunk 4]
```diff
@@ -31,13 +48,26 @@ class HttpRedirect {
...
                     url.parameters.clear()
 
+                    /**
+                     * Disallow redirect with a security downgrade.
+                     */
+                    if (originProtocol.isSecure() && !url.protocol.isSecure()) {
+                        return call
+                    }
+
+                    if (originAuthority != url.authority) {
```
Comment (cy6erGn0m) [inline ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt]: Should we only check for auth/host/port or we need to check path as well?

File: ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt (hunk 2 above)
Comment (cy6erGn0m) [inline ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt]: It looks like we need HSTS support here as well

File: ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt (hunk 4 above)
Comment (e5l) [reply ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpRedirect.kt]: Path is ok. We should only check for `authority` part of the url: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax

**Comment by cy6erGn0m** [comment]
I'am going to fix it separately.

File: ktor-http/common/src/io/ktor/http/URLBuilder.kt (hunk 1 above)
Comment (dtretyakov) [reply ktor-http/common/src/io/ktor/http/URLBuilder.kt]: @cy6erGn0m, you are right, authority should be composed like that:
```
authority = [userinfo@]host[:port]
```
so if the port if default we should not add it at all.
We could cover it by tests as well.
