### PR TITLE
Switch conditional branch PlatformUtils.IS_NODE and PlatformUtils.IS_BROWSER

### LINKED ISSUE #1674: "TypeError: this.local$body.on is not a function" on ktor-client-js with node-fetch environment
**Ktor Version and Engine Used (client or server and name)**
Version: 1.3.1
Engine: Js-Client

**Describe the bug**
The module specifying `js { nodejs() }` and building called from JavaScript, throws "TypeError".

For example, the code blow.

```kotlin
private const val HOSTNAME = "sparql.crssnky.xyz"
private const val ENDPOINT = "/spql/imas/query"

val client = HttpClient(Js) {
    defaultRequest {
        accept(ContentType("application", "sparql-results+json"))
    }
    install(JsonFeature) {
        serializer = KotlinxSerializer(Json.nonstrict)
        acceptContentTypes += ContentType("application", "sparql-results+json")
    }
}

// -> Throws "TypeError: this.local$body.on is not a function"! 
val response = httpClient.get<Response>(buildQuery()) {
    url {
        protocol = URLProtocol.HTTPS
        host = HOSTNAME
    }
}

private fun buildQuery(): String = buildString {
    append(ENDPOINT)
    append("?output=json")
    append("&query=")

    val query = """
        some queries...
    """.trimIndent()

    append(URLEncoder.encode(query))
}

@Serializable
data class Response(...)
```

Repository URL: https://github.com/subroh0508/ktor-client-mpp-sample/tree/by-node-fetch

**Expected behavior**
Does not throw any errors on node-fetch environment.

**Screenshots**
MacScreenShot 2020-02-24 23 13 39

### PR DESCRIPTION
**Pull request by subroh0508**
**Subsystem**
Js-Client

**Motivation**
Fixes #1674 .

**Solution**
`Response#body` returns `ReadableStream`. But, it does not have `on` method.
So I replaced `Response#arrayBuffer` method instead of `ReadableStream` methods on `CoroutineScope.readBodyNode`.

And I use `jsRequire`, always throws `"Error loading module 'node-fetch': Error: Cannot find module 'node-fetch'"`. So, I deleted the method.

The operation has been confirmed in my sample repository.

### CODE REVIEW

**Comment by e5l** [comment]
Hi @subroh0508, thanks for the PR. 
It looks like the issue problem is different. Btw it looks like `arrayBuffer` doesn't work well with streaming body or long polling, could you add some tests to check that?

**Comment by subroh0508** [comment]
@e5l I see. The issue problem is using `node-fetch`, despite being able to access `window.fetch`, isn't it?

Fixed my code, and I'm glad if you can review.

File: ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt [hunk 1]
```diff
@@ -22,10 +22,10 @@ internal suspend fun commonFetch(
         controller.abort()
     }
 
-    val promise: Promise<Response> = if (PlatformUtils.IS_NODE) {
-        jsRequire("node-fetch")(input, init)
-    } else {
+    val promise: Promise<Response> = if (PlatformUtils.IS_BROWSER) {
```
Comment (e5l) [inline ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt]: We saw that sometimes it can work in the opposite. Let's dig in some details: could you tell me the values of the internal predicates in `PlatformUtils.IS_BROWSER` and `IS_NODE` on your platform? Maybe we can force them to work well on each platform.

Comment (subroh0508) [reply ktor-client/ktor-client-core/js/src/io/ktor/client/engine/js/compatibility/Utils.kt]: On my platform at the line

```
console.log(window)
// -> global {parent: global, postMessage: f, blur: f, ...}
console.log(window.document)
// -> document { URL: "http://localhost:8088/", activeElement: body, ... }

console.log(process)
// -> process {version: "v12.8.1", versions: {...}, arch: "x64", platform: "darwin", ...}
console.log(process.versions)
// -> {node: "12.8.1", v8: "7.8.279.23-electron.0". uv: "1.30.1", ...}
console.log(process.versions.node)
// -> "12.8.1"
```

**Comment by e5l** [comment]
Thanks a lot. Will be merged after the remote run!
